[package]
name = "rfont-types"
version.workspace = true
edition = "2024"
description = "rfont 字体库的类型定义和基础 trait"
authors = ["lghuahua"]
license = "MIT"
repository = "https://github.com/lghuahua/rfont"
publish = false  # 不发布到 crates.io，作为内部依赖

[dependencies]
font_macros = { path = "../rfont-macros" }
thiserror = { workspace = true }

[package.metadata.release]
tag = false
shared-version = "core"