[package]
name = "rfont-core"
version = "0.2.0"
edition = "2024"
description = "rfont 字体库的核心功能模块"
authors = ["lghuahua"]
license = "MIT"
repository = "https://github.com/lghuahua/rfont"
publish = false  # 不发布到 crates.io，作为内部依赖

[dependencies]
rfont-types = { path = "../rfont-types" }
tracing = "0.1"
font_macros = { path = "../../font_macros" }
encoding_rs = { workspace = true }
lru = { workspace = true }
brotli = { workspace = true }
