[package]
name = "rfont-core"
version = "0.1.0"
edition = "2021"
description = "rfont 字体库的核心功能模块"
authors = ["rfont Team"]
license = "MIT OR Apache-2.0"

[dependencies]
rfont-types = { path = "../rfont-types" }
font_macros = { path = "../../font_macros" }
chrono = { workspace = true }
encoding_rs = { workspace = true }
lru = { workspace = true }
brotli = { workspace = true }
